### ISSUE TITLE
ad.principal('missinguser') results in a traceback

### ISSUE THREAD

**Issue by pmbuko** [ftiff/pymacad#1]
``` text
>>> ad.principal('missinguser')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pymacad/ad/__init__.py", line 56, in principal
    output = _cmd_dscl_search(user_path)
  File "/Library/Python/2.7/site-packages/pymacad/ad/__init__.py", line 25, in _cmd_dscl_search
    stderr=subprocess.STDOUT)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['dscl', '/Search', 'read', '/Users/missinguser', 'AuthenticationAuthority']' returned non-zero exit status 56
```

Should probably catch the error in case of typo or user not in AD.

**Comment by kylecrawshaw** [comment]
I created a pull request that checks this and adds a couple of other functions

**Comment by kylecrawshaw** [comment]
This is now fixed with newly added changes
